- web/src/components/Vnc/index.js
- web/src/components/Vnc/style.scss
- web/src/components/VncList/index.js
- web/src/components/VncList/style.scss
> Fullscreen mode

- web/src/components/Vnc/index.js
- web/src/components/Vnc/style.scss
- web/src/components/VncList/index.js
- web/src/components/VncList/style.scss
> New disconnected/connecting view

- web/package.json
- web/src/index.ejs
- web/src/index.js
- web/webpack.config.js
- web/yarn.lock
this helps with unwanted browser cache
> generate html to add webpack build hash

- main.go
> remove -debug flag

- .travis.yml
- web/src/components/Log/index.js
http://technosophos.com/2014/06/11/compile-time-string-in-go.html
> return tag in version

- .travis.yml
- README.md
- docker-compose.yml
- docs/contributing.adoc
- docs/index.adoc
- main.go
- vendor/vendor.json
- web/src/components/Log/index.js
- web/src/components/Vnc/VncScreen.js
- web/src/containers/Viewport/index.js
- web/webpack.config.js
> proxy websockets via backend

- web/src/containers/Capabilities/index.js
Example:
```python
capabilities = {"browserName": "chrome","version": "59.0"}
driver = webdriver.Remote(
command_executor="http://selenoid-uri:4444/wd/hub",
desired_capabilities=capabilities)
```
> Added example python capabilities

- web/src/components/Navigation/style.scss
- web/src/containers/Viewport/style.scss
> remove menu overlap with stats block

- web/package.json
- web/src/components/LogList/index.js
- web/src/components/Navigation/index.js
- web/src/components/Navigation/style.scss
- web/src/components/Status/index.js
- web/src/components/Status/style.scss
- web/src/containers/Stats/index.js
- web/src/containers/Viewport/index.js
- web/src/containers/Viewport/style.scss
- web/src/index.js
- web/webpack.config.js
- web/yarn.lock
> Reconnect to sse on failures

- web/package.json
- web/src/components/Session/style.scss
- web/src/components/Sessions/style.scss
- web/src/containers/Viewport/index.js
- web/yarn.lock
> fix win issues (add event source polifyll)

- web/src/components/VncCard/VncScreen.js
Fixed VNC connect  port when use default port
```js
const link = urlTo("https://github.com")
link.port // ""
```
> Fixed VNC connect  port when use default port

- web/src/components/VncCard/VncScreen.js
> fix typo in logical expression for default port

- web/src/components/Log/index.js
- web/src/components/Navigation/style.scss
- web/src/components/Session/style.scss
- web/src/components/Sessions/index.js
- web/src/components/Sessions/style.scss
- web/src/components/VncCard/index.js
- web/src/containers/Stats/style.scss
- web/src/containers/Viewport/index.js
- web/src/containers/Viewport/style.scss
> swap caps and sessions tabs

- web/src/components/Sessions/style.scss
> add padding to session list

- web/package.json
- web/src/containers/Viewport/index.js
- web/src/containers/Viewport/style.scss
- web/src/index.js
- web/sse-example.json
- web/yarn.lock
> fix issue with more than 10 sessions

- web/package.json
- web/src/components/Log/index.js
- web/yarn.lock
> rx terminal component, use standard decoder

- web/package.json
- web/src/components/Log/index.js
- web/src/components/Session/SessionInfo.js
- web/src/components/Session/index.js
- web/src/components/Session/style.scss
- web/src/containers/Stats/style.scss
- web/src/containers/Viewport/style.scss
- web/yarn.lock
> don't load vnc and logs if session not found in sse update

- Gopkg.lock
- web/src/components/Log/index.js
- web/src/components/VncCard/VncScreen.js
- web/src/util/isSecure.js
> support wss

- web/package.json
- web/src/components/Session/index.js
- web/yarn.lock
> return to sessions list after current is closed

- web/src/components/Log/index.js
- web/src/components/Log/style.scss
- web/src/components/Session/index.js
- web/src/components/VncCard/index.js
> Hide log on vnc fullscreen

- ui/src/containers/Stats/style.scss
Hey guys - we use your software pretty extensively and have many browsers installed, but your UI only allows for 5 or 6 browsers before the CSS in the UI clips out. When you have more than that it is annoying to click around!
This should fix that but let me know if you have any questions.
> Added support for more than 5 browsers

- ui/package.json
- ui/src/components/Browsers/Browser.js
- ui/src/components/Navigation/index.js
- ui/src/components/Queue/index.js
- ui/src/components/Quota/index.js
- ui/src/components/Sessions/index.js
- ui/src/components/Status/index.js
- ui/src/components/Videos/index.js
- ui/src/containers/Capabilities/index.js
- ui/src/containers/Stats/index.js
- ui/src/containers/Viewport/index.js
- ui/yarn.lock
Quite a simple refactoring, using functional components where easily possible
> functional components, react-scripts 3.0.1

- selenoid/selenoid.go
- ui/src/components/Sessions/index.js
- ui/src/components/Sessions/style.css.js
- ui/src/components/Stats/Separator.js
- ui/src/components/Stats/StatsElement.js
- ui/src/containers/Capabilities/index.js
- ui/src/containers/Viewport/index.js
> Table view for sessions

- ui/src/components/Videos/index.js
- ui/src/components/Videos/style.css.js
- ui/src/containers/Viewport/index.js
> Filter videos

- ui/src/components/Videos/index.js
- ui/src/components/Videos/style.css.js
> align long video names properly, add video link

- main.go
- selenoid/selenoid.go
- selenoid/selenoid_test.go
- ui/src/components/Stats/Status.js
- ui/src/containers/Viewport/index.js
- ui/src/sse-example.json
Partially fixes #241
just hover on sse status
> Add version of UI as title to status

- .travis.yml
- Dockerfile
- healthcheck/main.go
> add docker healthcheck

- ui/src/components/Browsers/Browser.js
- ui/src/components/Browsers/index.js
- ui/src/components/Stats/Queue.js
- ui/src/components/Stats/Quota.js
- ui/src/components/Stats/Used.js
- ui/src/containers/Capabilities/index.js
- ui/src/containers/Stats/index.js
- ui/src/containers/Viewport/index.js
> better unknown state representation, titles for quota

- ui/src/components/Videos/index.js
- ui/src/components/Videos/service.js
- ui/src/components/Videos/style.css.js
> delete video button

- ui/src/containers/Capabilities/index.js
- ui/src/containers/Capabilities/style.css.js
Simple toggleable textarea with additional capabilities to use in the selenoid-ui
> ability to define additonal capabilities

- Dockerfile
> reduce the healthcheck rate to 30s

- ui/package.json
- ui/yarn.lock
Bump eslint-plugin-prettier to 4.2.1
> build: Bump eslint-plugin-prettier to 4.2.1

- browsers.json
update chrome image version to 112
> update chrome image version to 112
